import "./globals.css";
import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/sonner";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { StoreProvider } from "@/store/provider";
import UserProfile from "@/components/user-profile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-[url('/assets/images/background.png')] bg-no-repeat light`}
      >
        <NextTopLoader
          showSpinner={false}
          easing="ease"
          color="#fff"
          height={3}
        />
        <StoreProvider>
          {children}
          <UserProfile />
        </StoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
